import Head from 'next/head'
import Typewriter from 'typewriter-effect';
import Navbar from '../components/Navbar';
import { motion } from 'framer-motion';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Rohan Singh | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
    <motion.section 
               initial={{
                opacity: 0
               }}
               animate={{
                opacity: 1,
                transition: {
                    duration: 0.3
                }
               }}
    className='relative'>
      <div className='flex justify-evenly mt-10'>
        <div className='w-8/2 h-[22rem] md:h-[60vh] md:w-[60vw] lg:h-[100vh] lg:w-[70vw] flex items-center flex-col justify-center md:-mt-10 lg:-mt-16'>
        <div className='absolute left-2 md:left-12 -mt-24 lg:left-20'>
        <h1 className='text-xl md:text-2xl lg:text-5xl text-center'><sup> Hi,</sup> I'm <span className='text-blue-600'> Rohan </span>Singh </h1>
        <h2 className='text-md md:text-lg lg:text-2xl text-center mt-2 flex absolute left-6 lg:left-14 w-52 md:w-72'><span className='text-lg md:text-2xl lg:text-3xl'> I </span><span className='text-red-700 text-sm md:text-xl mt-1'>&nbsp; ❤ &nbsp;</span>&nbsp;<span className='text-blue-600 text-lg md:text-xl lg:text-2xl'>
        <Typewriter
          options={{
            strings: ['Web Designing', 'Web Development'],
            autoStart: true,
            loop: true,
          }}/>
        </span></h2>
        </div>
        </div>
      <img src="img1.png" className='h-96 md:h-[60vh] lg:h-[100vh] fixed right-0 md:right-20 lg:right-36 -z-10'/>
      </div>
    </motion.section>
    <section className='bg-white'>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim autem reprehenderit fugiat necessitatibus accusamus deleniti, laboriosam aspernatur excepturi saepe provident! Dolorum necessitatibus odit quis minima cupiditate doloremque itaque, atque ea! Sequi, illo temporibus autem ad sed nulla natus, nemo a impedit repellendus incidunt laboriosam quae in necessitatibus modi soluta esse. Quo, error. Eum dignissimos excepturi, consequuntur quam, unde, exercitationem consequatur sed harum nisi voluptas dicta optio enim. Quae laboriosam soluta fugit voluptatum aperiam cupiditate nemo doloribus aut rerum ab praesentium officia culpa commodi dolore consequatur, nihil id! Dolorem, molestiae? Quod voluptatibus magnam quaerat quia dolore vel vitae sed, debitis molestiae.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim autem reprehenderit fugiat necessitatibus accusamus deleniti, laboriosam aspernatur excepturi saepe provident! Dolorum necessitatibus odit quis minima cupiditate doloremque itaque, atque ea! Sequi, illo temporibus autem ad sed nulla natus, nemo a impedit repellendus incidunt laboriosam quae in necessitatibus modi soluta esse. Quo, error. Eum dignissimos excepturi, consequuntur quam, unde, exercitationem consequatur sed harum nisi voluptas dicta optio enim. Quae laboriosam soluta fugit voluptatum aperiam cupiditate nemo doloribus aut rerum ab praesentium officia culpa commodi dolore consequatur, nihil id! Dolorem, molestiae? Quod voluptatibus magnam quaerat quia dolore vel vitae sed, debitis molestiae.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim autem reprehenderit fugiat necessitatibus accusamus deleniti, laboriosam aspernatur excepturi saepe provident! Dolorum necessitatibus odit quis minima cupiditate doloremque itaque, atque ea! Sequi, illo temporibus autem ad sed nulla natus, nemo a impedit repellendus incidunt laboriosam quae in necessitatibus modi soluta esse. Quo, error. Eum dignissimos excepturi, consequuntur quam, unde, exercitationem consequatur sed harum nisi voluptas dicta optio enim. Quae laboriosam soluta fugit voluptatum aperiam cupiditate nemo doloribus aut rerum ab praesentium officia culpa commodi dolore consequatur, nihil id! Dolorem, molestiae? Quod voluptatibus magnam quaerat quia dolore vel vitae sed, debitis molestiae.
    </section>
    </>
  )
}
