import Head from 'next/head'
import Typewriter from 'typewriter-effect';
import { motion } from 'framer-motion';
import Navbar from '../components/Navbar';
import { useState } from 'react';
import { AiFillGithub } from 'react-icons/ai';

export default function Home() {
  const [education, setEducation] = useState( true )
  const [experience, setExperience] = useState( false )
  const [skills, setSkills] = useState( false )

  const handleEducation = () => {
    setEducation( true )
    setExperience( false )
    setSkills( false )
  }
  const handleExperience = () => {
    setEducation( false )
    setExperience( true )
    setSkills( false )
  }
  const handleSkills = () => {
    setEducation( false )
    setExperience( false )
    setSkills( true )
  }
  const aboutVariants = {
    hidden: {
      opacity: 0
    },
    visible: {
      opacity: 1,
      transition: {
        duration: 0.3,
        when: "beforeChildren",
        staggerChildren: 0.3
      }
    }
  }
  const innerAboutVariants = {
    hidden: {
      opacity: 0,
      x: '-60vw'
    },
    visible: {
      opacity: 1,
      x: 0,
      transition: {
        duration: 0.2,
        type: 'spring',
        when: "afterChildren"
      }
    }
  }
  return (
    <>
      <Head>
        <title>Rohan Singh | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ------------------------navbar----------------------- */}
      <Navbar />
      {/* ------------------------home----------------------- */}
      <motion.section
        initial={{
          opacity: 0
        }}
        animate={{
          opacity: 1,
          transition: {
            duration: 0.3
          }
        }}
        className='relative' id='home'>
        <div className='flex justify-evenly mt-10'>
          <div className='w-8/2 h-[22rem] md:h-[60vh] md:w-[60vw] lg:h-[100vh] lg:w-[70vw] flex items-center flex-col justify-center md:-mt-10 lg:-mt-16'>
            <div className='absolute left-2 md:left-12 -mt-24 lg:left-20'>
              <h1 className='text-xl md:text-2xl lg:text-5xl text-center'><sup className='text-slate-700'> hi,</sup> I'm <span className='text-blue-600'> Rohan </span>Singh </h1>
              <h2 className='text-md md:text-lg lg:text-2xl text-center mt-2 flex absolute left-6 lg:left-14 w-52 md:w-72'><span className='text-lg md:text-2xl lg:text-3xl'> I </span><span className='text-red-700 text-sm md:text-xl mt-1'>&nbsp; ❤ &nbsp;</span>&nbsp;<span className='text-blue-600 text-lg md:text-xl lg:text-2xl'>
                <Typewriter
                  options={{
                    strings: ['Web Designing', 'Web Development'],
                    autoStart: true,
                    loop: true,
                  }} />
              </span></h2>
            </div>
          </div>
          <img src="img1.png" className='h-96 md:h-[60vh] lg:h-[100vh] fixed right-0 md:right-20 lg:right-36 -z-10' />
        </div>
      </motion.section>
      {/* ------------------------about----------------------- */}
      <motion.section
        initial={{
          opacity: 0
        }}
        animate={{
          opacity: 1,
          transition: {
            duration: 0.3
          }
        }}
        id="about" className='bg-white flex justify-center md:justify-around flex-wrap py-6'>
        <div className='w-64 h-64 bg-orange-400 rounded-lg'>

        </div>
        <div className='lg:w-6/12 md:w-5/12'>
          <h2 className='md:text-lg lg:text-xl text-blue-600 font-semibold'>About me</h2>
          <p className='text-xs text-slate-700'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam repellat aperiam facilis rem. Suscipit delectus voluptates repudiandae atque, corrupti recusandae velit aperiam voluptas qui in harum adipisci vero reiciendis non.</p>
          <ul className='flex md:space-x-4 lg:space-x-6 my-2 border-b-2 pb-1'>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleEducation() }} className={`cursor-pointer ${education && 'underline-offset-4 underline text-blue-600'}`}>Education</motion.li>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleExperience() }} className={`cursor-pointer ${experience && 'underline-offset-4 underline text-blue-600'}`}>Experience</motion.li>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleSkills() }} className={`cursor-pointer ${skills && 'underline-offset-4 underline text-blue-600'}`}>Skills</motion.li>
          </ul>
          {education && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible"
          >
            <ul
              className='list-disc space-y-4 mt-6'>
              <motion.div
                variants={innerAboutVariants}
                className='flex items-center'>
                <li className='text-blue-600'><strong>10 </strong><sup> th</sup> :</li><span className='ml-2 text-xs md:text-sm text-slate-900'>From WBBSE(2019) with 65%.</span></motion.div>
              <motion.div
                variants={innerAboutVariants}
                className='flex'>
                <li className='text-blue-600'><strong>12 </strong><sup> th</sup> :</li><span className='ml-2 text-xs md:text-sm text-slate-900'>From WBCHSE(2021) with 70.8%.</span></motion.div>
              <motion.div
                variants={innerAboutVariants}
                className='flex'>
                <li className='text-blue-600'><strong>Graduation</strong> :</li><span className='ml-2 text-xs md:text-sm text-slate-900'>Persuing Batchelor Of Technology(2021-25) from Swami Vivekananda University</span></motion.div>
            </ul>
          </motion.div>}
          {experience && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible">
            <ul className='list-disc space-y-4 mt-6'>
              <motion.li
                variants={innerAboutVariants} className='text-blue-600'><strong> Fresher till now.</strong></motion.li>
            </ul>
          </motion.div>}
          {skills && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible">
            <ul className='list-disc space-y-4 mt-6'>
              <motion.li
                variants={innerAboutVariants}
                className='text-blue-600'><strong>Web Development</strong></motion.li>
              <motion.li
                variants={innerAboutVariants}
                className='text-blue-600'><strong>Web Designing</strong></motion.li>
            </ul>
          </motion.div>}
        </div>
      </motion.section>
      {/* ------------------------projects----------------------- */}
      <section id='projects' className='bg-white md:px-12 lg:px-24 py-6 md:py-10 opacity-[2]'>
        <h1 className='text-lg md:text-xl lg:text-3xl text-center md:text-start font-semibold text-blue-600'>My Recent Projects</h1>
        <div className="flex flex-wrap md:my-6 justify-evenly cursor-pointer space-y-4 md:space-y-2 lg:space-y-0">
          <a href="#">
          <motion.div 
            whileHover={{
              scale: 1.05,
              transition: {
                duration: 0.3
              }
            }}
            whileTap={{
              scale: 0.9
            }}
            className='w-64 h-64 bg-orange-300 rounded-lg relative mt-4 md:mt-2 lg:mt-0'>
            <img 
            className='absolute rounded-lg inset-0 w-full h-full object-cover object-center' src="https://s3.amazonaws.com/gdb-blog/images/graphenedb-security.png"/>
            <motion.div
            initial={{
              opacity: 0,
            }}
            whileHover={{
              opacity: 1,
              transition:{
                duration: 0.5
              }
            }}
            className='relative rounded-lg z-10 w-full min-h-full p-4 bg-[#ffffffdc]'>
              <div className='flex flex-col justify-center items-center'>
            <h2 class="tracking-widest text-sm title-font font-medium text-green-600 mb-1">Django</h2>
            <h1 class="title-font text-xl font-semibold text-blue-700 mb-3">Authentication System</h1>
            <p className='text-xs text-green-600 -mt-3 mb-4 ml-auto'>~ Completed</p>
            <p class="leading-relaxed text-slate-800">This Authentication System fully make in Django which is a python Framework.</p>
            </div>
            <div className='absolute bottom-2 right-3 flex'>
            <p className='text-xs md:text-sm mx-2 text-slate-600'>Show it on </p><AiFillGithub className='text-xl'/></div>
            </motion.div>
            <div className='absolute bottom-1 right-2 flex md:hidden'>
            <p className='text-xs md:text-sm mx-2 text-black'>Show it on </p><AiFillGithub className='text-xl'/></div>
          </motion.div>
          </a>
          <div className='w-64 h-64 bg-orange-300 rounded-lg'>

          </div>
          <div className='w-64 h-64 bg-orange-300 rounded-lg'>

          </div>
          <div className='w-64 h-64 bg-orange-300 rounded-lg'>

          </div>
        </div>
      </section>
    </>
  )
}
