import Head from 'next/head'
import Typewriter from 'typewriter-effect';
import { motion } from 'framer-motion';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { AiFillGithub, AiOutlineInstagram, AiFillLinkedin, AiOutlineMail, AiFillTwitterCircle } from 'react-icons/ai';
import { FiPhoneCall } from 'react-icons/fi';


export default function Home() {
  const [education, setEducation] = useState( true )
  const [experience, setExperience] = useState( false )
  const [skills, setSkills] = useState( false )

  const handleEducation = () => {
    setEducation( true )
    setExperience( false )
    setSkills( false )
  }
  const handleExperience = () => {
    setEducation( false )
    setExperience( true )
    setSkills( false )
  }
  const handleSkills = () => {
    setEducation( false )
    setExperience( false )
    setSkills( true )
  }
  const aboutVariants = {
    hidden: {
      opacity: 0
    },
    visible: {
      opacity: 1,
      transition: {
        duration: 0.3,
        when: "beforeChildren",
        staggerChildren: 0.3
      }
    }
  }
  const innerAboutVariants = {
    hidden: {
      opacity: 0,
      x: '-60vw'
    },
    visible: {
      opacity: 1,
      x: 0,
      transition: {
        duration: 0.2,
        type: 'spring',
        when: "afterChildren"
      }
    }
  }
  return (
    <>
      <Head>
        <title>Rohan Singh | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ------------------------navbar----------------------- */}
      <Navbar />
      {/* ------------------------home----------------------- */}
      <motion.section
        initial={{
          opacity: 0
        }}
        animate={{
          opacity: 1,
          transition: {
            duration: 0.3
          }
        }}
        className='relative md:px-6' id='home'>
        <div className='flex justify-evenly mt-10'>
          <div className='w-8/2 h-[22rem] md:h-[60vh] md:w-[60vw] lg:h-[100vh] lg:w-[70vw] flex items-center flex-col justify-center md:-mt-10 lg:-mt-16'>
            <div className='absolute left-2 md:left-12 -mt-24 lg:left-20'>
              <h1 className='text-xl md:text-2xl lg:text-5xl text-center'><sup className='text-slate-700'> hi,</sup> I'm <span className='text-blue-600'> Rohan </span>Singh </h1>
              <h2 className='text-md md:text-lg lg:text-2xl text-center mt-2 flex absolute left-6 lg:left-14 w-52 md:w-72'><span className='text-lg md:text-2xl lg:text-3xl'> I </span><span className='text-red-700 text-sm md:text-xl mt-1'>&nbsp; ❤ &nbsp;</span>&nbsp;<span className='text-blue-600 text-lg md:text-xl lg:text-2xl'>
                <Typewriter
                  options={{
                    strings: ['Web Designing', 'Web Development'],
                    autoStart: true,
                    loop: true,
                  }} />
              </span></h2>
            </div>
          </div>
          <img src="img1.png" className='h-96 md:h-[60vh] lg:h-[100vh] fixed right-0 md:right-20 lg:right-36 -z-10' />
        </div>
      </motion.section>
      {/* ------------------------about----------------------- */}
      <motion.section
        initial={{
          opacity: 0
        }}
        animate={{
          opacity: 1,
          transition: {
            duration: 0.3
          }
        }}
        id="about" className='bg-white flex justify-center md:justify-around flex-wrap px-6 pt-8'>
        <div className='w-52 h-52 md:w-64 md:h-64 bg-orange-400 rounded-lg'>

        </div>
        <div className='lg:w-6/12 md:w-5/12'>
          <h2 className='md:text-lg lg:text-xl text-blue-600 font-semibold text-center md:text-start'>About me</h2>
          <p className='text-xs text-slate-700 px-6 md:px-2 text-center md:text-start'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam repellat aperiam facilis rem. Suscipit delectus voluptates repudiandae atque, corrupti recusandae velit aperiam voluptas qui in harum adipisci vero reiciendis non.</p>
          <ul className='flex space-x-3 md:space-x-6 mt-4 mb-2 border-b-2 pb-1'>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleEducation() }} className={`cursor-pointer ${education && 'underline-offset-4 underline text-blue-600'}`}>Education</motion.li>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleExperience() }} className={`cursor-pointer ${experience && 'underline-offset-4 underline text-blue-600'}`}>Experience</motion.li>
            <motion.li
              whileHover={{
                y: -3,
                scale: 1.1,
                transition: {
                  duration: 0.2
                }
              }}
              whileTap={{
                scale: 0.9
              }}
              onClick={() => { handleSkills() }} className={`cursor-pointer ${skills && 'underline-offset-4 underline text-blue-600'}`}>Skills</motion.li>
          </ul>
          {education && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible"
          >
            <ul
              className='list-disc space-y-4 pt-2 lg:mt-3'>
              <motion.div
                variants={innerAboutVariants}
                className='flex items-center'>
                <li className='text-blue-600'><strong>10 </strong><sup> th</sup> :</li><span className='ml-2 text-xs md:text-sm text-slate-900'>From WBBSE(2019) with 65%.</span></motion.div>
              <motion.div
                variants={innerAboutVariants}
                className='flex'>
                <li className='text-blue-600'><strong>12 </strong><sup> th</sup> :</li><span className='ml-2 text-xs md:text-sm text-slate-900'>From WBCHSE(2021) with 70.8%.</span></motion.div>
              <motion.div
                variants={innerAboutVariants}
                className='flex'>
                <li className='text-blue-600'><strong>Graduation</strong>&nbsp;:</li><span className='ml-2 text-xs md:text-sm text-slate-900'>Persuing Batchelor Of Technology(2021-25) from Swami Vivekananda University</span></motion.div>
            </ul>
          </motion.div>}
          {experience && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible">
            <ul className='list-disc space-y-4 pt-2 lg:mt-3'>
              <motion.li
                variants={innerAboutVariants} className='text-blue-600'><strong> Fresher till now.</strong></motion.li>
            </ul>
          </motion.div>}
          {skills && <motion.div
            variants={aboutVariants}
            initial="hidden"
            animate="visible">
            <ul className='list-disc space-y-4 pt-2 lg:mt-3'>
              <motion.li
                variants={innerAboutVariants}
                className='text-blue-600'><strong>Web Development</strong></motion.li>
              <motion.li
                variants={innerAboutVariants}
                className='text-blue-600'><strong>Web Designing</strong></motion.li>
            </ul>
          </motion.div>}
        </div>
      </motion.section>
      {/* ------------------------languages----------------------- */}
      <section id='languages' className='flex flex-col space-y-4 md:space-y-6 bg-white md:px-16 lg:px-28 py-8 md:py-10'>
        <h1 className='text-xl md:text-2xl lg:text-4xl text-blue-600 font-semibold'>Programming Languages</h1>
        <p>Here are some Programming languages or skills known by me.</p>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>HTML</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[50vw] rounded-xl absolute'></div>
          </div>
          <span>80%</span>
        </div>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>CSS</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[42vw] rounded-xl absolute'></div>
          </div>
          <span>60%</span>
        </div>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>Java&nbsp;Script</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[36vw] rounded-xl absolute'></div>
          </div>
          <span>60%</span>
        </div>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>Python</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[36vw] rounded-xl absolute'></div>
          </div>
          <span>60%</span>
        </div>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>Django</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[42vw] rounded-xl absolute'></div>
          </div>
          <span>70%</span>
        </div>
        <div className='flex px-2 space-x-2 md:space-x-4 items-center'>
          <span className='w-20 text-center'>Next.js</span>
          <div className='h-4 md:h-5 border w-full rounded-xl md:w-[60vw] relative bg-blue-50'>
            <div className='h-full bg-blue-500 w-[42vw] rounded-xl absolute'></div>
          </div>
          <span>70%</span>
        </div>
      </section>
      {/* ------------------------projects----------------------- */}
      <section
        id='projects' className='bg-white md:px-12 lg:px-24 pb-16 pt-4 md:py-10 opacity-[2] relative'>
        <h1 className='text-xl md:text-2xl lg:text-3xl text-center lg:text-start font-semibold text-blue-600'>My Recent Projects</h1>
        <p className='text-slate-700 text-center lg:text-start'>Here is the all of my Recent Project Section. If you want to see the code just Click on it.</p>
        <div className="flex flex-col md:flex-row flex-wrap md:my-6 items-center md:justify-evenly cursor-pointer space-y-6 md:space-y-4 lg:space-y-0 mt-6">
          <motion.div
            whileHover={{
              y: -5,
              transition: {
                duration: 0.3
              }
            }}
            whileTap={{
              scale: 0.9
            }}
            className='w-64 h-64 rounded-lg relative mt-4 md:mt-2 lg:mt-0 hover:shadow-2xl hover:border-2'>
            <a href="#">
              <img
                className='absolute rounded-lg inset-0 w-full h-full object-cover object-center hover:opacity-50' src="https://s3.amazonaws.com/gdb-blog/images/graphenedb-security.png" />
              <motion.div
                initial={{
                  opacity: 0,
                }}
                whileHover={{
                  opacity: 1,
                  transition: {
                    duration: 0.5
                  }
                }}
                className='relative rounded-lg z-10 w-full min-h-full p-4 bg-gradient-to-t from-blue-500 to-[#ffffffdc]'>
                <div className='flex flex-col justify-center items-center'>
                  <h2 class="tracking-widest text-sm title-font font-medium text-green-600 mb-1">Django</h2>
                  <h1 class="title-font text-xl font-semibold text-blue-700 mb-3">Authentication System</h1>
                  <p className='text-xs text-green-600 -mt-3 mb-4 ml-auto'>~ Completed</p>
                  <p class="leading-relaxed text-slate-800">This Authentication System fully make in Django which is a python Framework.</p>
                </div>
                <div className='absolute bottom-2 right-3 flex'>
                  <p className='text-xs md:text-sm mx-2 text-white'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
              </motion.div>
              <div className='absolute bottom-1 right-2 flex lg:hidden'>
                <p className='text-xs md:text-sm mx-2 text-black'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
            </a>
          </motion.div>
          <motion.div
            whileHover={{
              y: -5,
              transition: {
                duration: 0.3
              }
            }}
            whileTap={{
              scale: 0.9
            }}
            className='w-64 h-64 rounded-lg relative mt-4 md:mt-2 lg:mt-0 hover:shadow-2xl hover:border-2'>
            <a href="#">
              <img
                className='absolute rounded-lg inset-0 w-full h-full object-cover object-center' src="https://s3.amazonaws.com/gdb-blog/images/graphenedb-security.png" />
              <motion.div
                initial={{
                  opacity: 0,
                }}
                whileHover={{
                  opacity: 1,
                  transition: {
                    duration: 0.5
                  }
                }}
                className='relative rounded-lg z-10 w-full min-h-full p-4  bg-gradient-to-t from-blue-500 to-[#ffffffdc]'>
                <div className='flex flex-col justify-center items-center'>
                  <h2 class="tracking-widest text-sm title-font font-medium text-green-600 mb-1">Django</h2>
                  <h1 class="title-font text-xl font-semibold text-blue-700 mb-3">Authentication System</h1>
                  <p className='text-xs text-green-600 -mt-3 mb-4 ml-auto'>~ Completed</p>
                  <p class="leading-relaxed text-slate-800">This Authentication System fully make in Django which is a python Framework.</p>
                </div>
                <div className='absolute bottom-2 right-3 flex'>
                  <p className='text-xs md:text-sm mx-2 text-white'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
              </motion.div>
              <div className='absolute bottom-1 right-2 flex lg:hidden'>
                <p className='text-xs md:text-sm mx-2 text-black'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
            </a>
          </motion.div>
          <motion.div
            whileHover={{
              y: -5,
              transition: {
                duration: 0.3
              }
            }}
            whileTap={{
              scale: 0.9
            }}
            className='w-64 h-64 rounded-lg relative mt-4 md:mt-2 lg:mt-0 hover:shadow-2xl hover:border-2'>
            <a href="#">
              <img
                className='absolute rounded-lg inset-0 w-full h-full object-cover object-center' src="https://s3.amazonaws.com/gdb-blog/images/graphenedb-security.png" />
              <motion.div
                initial={{
                  opacity: 0,
                }}
                whileHover={{
                  opacity: 1,
                  transition: {
                    duration: 0.5
                  }
                }}
                className='relative rounded-lg z-10 w-full min-h-full p-4  bg-gradient-to-t from-blue-500 to-[#ffffffdc]'>
                <div className='flex flex-col justify-center items-center'>
                  <h2 class="tracking-widest text-sm title-font font-medium text-green-600 mb-1">Django</h2>
                  <h1 class="title-font text-xl font-semibold text-blue-700 mb-3">Authentication System</h1>
                  <p className='text-xs text-green-600 -mt-3 mb-4 ml-auto'>~ Completed</p>
                  <p class="leading-relaxed text-slate-800">This Authentication System fully make in Django which is a python Framework.</p>
                </div>
                <div className='absolute bottom-2 right-3 flex'>
                  <p className='text-xs md:text-sm mx-2 text-white'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
              </motion.div>
              <div className='absolute bottom-1 right-2 flex lg:hidden'>
                <p className='text-xs md:text-sm mx-2 text-black'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
            </a>
          </motion.div>
          <motion.div
            whileHover={{
              y: -5,
              transition: {
                duration: 0.3
              }
            }}
            whileTap={{
              scale: 0.9
            }}
            className='hidden md:block lg:hidden w-64 h-64 rounded-lg relative mt-4 md:mt-2 lg:mt-0 hover:shadow-2xl hover:border-2'>
            <a href="#">
              <img
                className='absolute rounded-lg inset-0 w-full h-full object-cover object-center' src="https://s3.amazonaws.com/gdb-blog/images/graphenedb-security.png" />
              <motion.div
                initial={{
                  opacity: 0,
                }}
                whileHover={{
                  opacity: 1,
                  transition: {
                    duration: 0.5
                  }
                }}
                className='relative rounded-lg z-10 w-full min-h-full p-4  bg-gradient-to-t from-blue-500 to-[#ffffffdc]'>
                <div className='flex flex-col justify-center items-center'>
                  <h2 class="tracking-widest text-sm title-font font-medium text-green-600 mb-1">Django</h2>
                  <h1 class="title-font text-xl font-semibold text-blue-700 mb-3">Authentication System</h1>
                  <p className='text-xs text-green-600 -mt-3 mb-4 ml-auto'>~ Completed</p>
                  <p class="leading-relaxed text-slate-800">This Authentication System fully make in Django which is a python Framework.</p>
                </div>
                <div className='absolute bottom-2 right-3 flex'>
                  <p className='text-xs md:text-sm mx-2 text-white'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
              </motion.div>
              <div className='absolute bottom-1 right-2 flex lg:hidden'>
                <p className='text-xs md:text-sm mx-2 text-black'>Click it to show the code on </p><AiFillGithub className='text-xl' /></div>
            </a>
          </motion.div>
          <motion.button
            whileHover={{
              scale: 1.05
            }}
            whileTap={{
              scale: 0.9
            }}
            className='absolute lg:right-44 bottom-2 py-2 px-4 text-blue-600 border border-blue-600 rounded-md hover:text-white hover:bg-blue-600 hover:shadow-blue-300 hover:shadow-md'>View more</motion.button>
        </div>
      </section>
      {/* ------------------------contact----------------------- */}
      <section id='contact' className='bg-white flex py-14 relative flex-wrap'>
        <div className='w-full md:w-1/2 flex flex-col justify-center items-center md:items-start md:pl-44 space-y-5'>
          <h2 className='text-4xl'>Contact me</h2>
          <div className='flex items-center cursor-pointer'><FiPhoneCall className='text-green-600 text-xl' /><p className='ml-2'> +91-6290653563</p></div>
          <div className='flex items-center cursor-pointer'><AiOutlineMail className='text-orange-600 text-xl' /><p className='ml-2'> rs7289579@gmail.com</p></div>
          <div className='flex space-x-4'>
            <AiOutlineInstagram className='text-3xl text-red-600 cursor-pointer' />
            <AiFillLinkedin className='text-3xl text-blue-600 cursor-pointer' />
            <AiFillTwitterCircle className='text-3xl text-cyan-400 cursor-pointer' />
            <AiFillGithub className='text-3xl cursor-pointer' />
          </div>
          <motion.a
            whileHover={{
              scale: 1.05
            }}
            whileTap={{
              scale: 0.9
            }}
            href="img1.png" download className='py-2 px-4 text-blue-600 border border-blue-600 rounded-md hover:text-white hover:bg-blue-600 hover:shadow-blue-300 hover:shadow-md'>Download CV</motion.a>
        </div>
        <div className='w-full md:w-1/2 flex flex-col space-y-4 px-12 mt-10 md:mt-0'>
          <input className='p-2 border rounded-md focus:shadow-blue-300 focus:shadow-lg focus:outline-none' type="text" name="name" placeholder='Enter Your Name' />
          <input className='p-2 border rounded-md focus:shadow-blue-300 focus:shadow-lg focus:outline-none' type="email" name="email" placeholder='Enter Your Email Id' />
          <textarea className='p-2 border rounded-md focus:shadow-blue-300 focus:shadow-lg focus:outline-none' name="address" id="address" cols="30" rows="6" placeholder='Enter your Address'></textarea>
          <motion.button
            whileHover={{
              scale: 1.05
            }}
            whileTap={{
              scale: 0.9
            }}
            className='absolute right-12 bottom-2 py-2 px-4 text-blue-600 border border-blue-600 rounded-md hover:text-white hover:bg-blue-600 hover:shadow-blue-300 hover:shadow-md'>Submit</motion.button>
        </div>
      </section>
      {/* ------------------------footer----------------------- */}
      <Footer />
    </>
  )
}
